version: '2.3'
services:
  statsd:
    image: hopsoft/graphite-statsd
    ports:
     - 80:80
     - 2003:2003
     - 2004:2004
     - 2023:2023
     - 2024:2024
     - 8125:8125/udp
     - 8126:8126
  servers:
    build: .
    scale: 6   
    expose:
     - "22"

