version: '3'
services:
#  servers:
#    image: hermsi/alpine-sshd
#    expose:
#     - "22"
  statsd:
    image: hopsoft/graphite-statsd
    ports:
     - 80:80
     - 2003-2004:2003:2004
     - 2023-2024:2023:2024
     - 8125:8125/udp
     - 8126:8126
  servers:
    build: .
    expose:
     - "22"

